language: cpp
dist: trusty

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      compiler: clang

before_install:
  - brew search llvm

script:
  - clang++ main.cpp -std=c++17 -stdlib=libc++ -v -o travis_gcc_cpp17
  - ./travis_gcc_cpp17
