language: cpp
dist: trusty

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      compiler: clang

before_install:
#  - brew search llvm

script:
  - brew update
  - brew search llvm
  - brew install llvm@5
  - LDFLAGS += -L/usr/local/opt/llvm@5/lib
  - CPPFLAGS += -I/usr/local/opt/llvm@5/include
  - clang --version
  - clang++ main.cpp -std=c++17 -stdlib=libc++ -v -o travis_gcc_cpp17
  - ./travis_gcc_cpp17
