language: cpp
dist: trusty

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      compiler: clang

before_install:
#  - brew search llvm

script:
  - brew update
  - brew search llvm
  - brew install llvm
  - clang --version
  - /usr/local/opt/llvm/bin/clang --version
  - echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.bash_profile
  - LDFLAGS += -L/usr/local/opt/llvm/lib
  - CPPFLAGS += -I/usr/local/opt/llvm/include
  - /usr/local/opt/llvm/bin/clang++ main.cpp -std=c++17 -stdlib=libc++ -v -o travis_gcc_cpp17
  - ./travis_gcc_cpp17
